version: 2
updates:
- package-ecosystem: npm
  directory: "/canaries"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/trivia-backend/app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/chat-bot/bot"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/trivia-backend/cdk"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: docker
  directory: "/trivia-backend/base"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/chat-bot/lex-model"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/pipelines"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/static-site/app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/static-site/cdk"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
