queue_rules:
  - name: default
    conditions:
      - status-success=Game App
      - status-success=Game Infra
      - status-success=Pipelines
      - status-success=Static Site

pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - base=master
      - author=dependabot[bot]
      - label=dependencies
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      queue:
        name: default
        method: squash
