version: 0.2

env:
  variables:
    STAGE: "dev"
    WEBSITE_BUCKET: ""

phases:
  build:
    commands:
      - cd static-site/
      - npm install -g npm@6.4.1
      - npm ci
      - npm run build:$STAGE
      - cp index.html build/
      - cd build/
      - if [ ! -z "$WEBSITE_BUCKET" ]; then aws s3 sync . s3://$WEBSITE_BUCKET; fi
