version: 0.2

env:
  variables:
    STAGE: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install dependencies for both site content and for CDK
      - npm install -g npm@latest
      - npm install -g aws-cdk
      - cd static-site/app
      - npm ci
      - cd ../cdk
      - npm ci
  build:
    commands:
      # Compile the site content
      - cd ../app/
      - npm run build:$STAGE
      - cp index.html error.html build/
      - cp -rf assets build/
      # Deploy via the CDK
      - cd ../cdk
      - npm run build
      - npm run bootstrap-infra
      - npm run deploy-infra-$STAGE
