AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chat bot for reInvent trivia game

Parameters:
  TriviaBackendEndpoint:
    Type: String
    Default: 'https://api.reinvent-trivia.com'

Resources:
  BotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lexv2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonLexRunBotsOnly

  TriviaBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Sub ${AWS::StackName}-TriviaGame
      Description: AWS re:Invent trivia game bot
      RoleArn: !GetAtt BotRole.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      BotLocales:
        - LocaleId: en_US
          Description: English US locale for trivia game
          NluConfidenceThreshold: 0.4
          VoiceSettings:
            VoiceId: Joanna
          Intents:
            - Name: FallbackIntent
              Description: Default intent when no other intent matches
              ParentIntentSignature: AMAZON.FallbackIntent
            - Name: LetsPlay
              Description: Main intent for playing the trivia game
              SampleUtterances:
                - Utterance: "Let's play"
                - Utterance: "Start the game"
                - Utterance: "Ask me another question"
                - Utterance: "I want to play the trivia game"
                - Utterance: "Play trivia"
                - Utterance: "Start"
              FulfillmentCodeHook:
                Enabled: true
              SlotPriorities:
                - Priority: 1
                  SlotName: one
                - Priority: 2
                  SlotName: two
                - Priority: 3
                  SlotName: three
                - Priority: 4
                  SlotName: four
                - Priority: 5
                  SlotName: five
                - Priority: 6
                  SlotName: six
                - Priority: 7
                  SlotName: seven
                - Priority: 8
                  SlotName: eight
                - Priority: 9
                  SlotName: nine
                - Priority: 10
                  SlotName: ten
                - Priority: 11
                  SlotName: eleven
                - Priority: 12
                  SlotName: twelve
                - Priority: 13
                  SlotName: thirteen
                - Priority: 14
                  SlotName: fourteen
                - Priority: 15
                  SlotName: fifteen
                - Priority: 16
                  SlotName: sixteen
              Slots:
                - Name: one
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: two
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: three
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: four
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: five
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: six
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: seven
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: eight
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: nine
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: ten
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: eleven
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: twelve
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: thirteen
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: fourteen
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: fifteen
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                - Name: sixteen
                  SlotTypeName: AMAZON.AlphaNumeric
                  ValueElicitationSetting:
                    SlotConstraint: Optional

  BotVersion:
    Type: AWS::Lex::BotVersion
    Properties:
      BotId: !Ref TriviaBot
      BotVersionLocaleSpecification:
        - LocaleId: en_US
          BotVersionLocaleDetails:
            SourceBotVersion: DRAFT

  BotAlias:
    Type: AWS::Lex::BotAlias
    Properties:
      BotId: !Ref TriviaBot
      BotAliasName: prod
      BotVersion: !GetAtt BotVersion.BotVersion
      BotAliasLocaleSettings:
        - LocaleId: en_US
          BotAliasLocaleSetting:
            Enabled: true
            CodeHookSpecification:
              LambdaCodeHook:
                LambdaArn: !Ref BotFunction.Alias
                CodeHookInterfaceVersion: "1.0"

  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bot
      Handler: bot.handler
      Runtime: nodejs20.x
      Timeout: 60
      Environment:
        Variables:
          API_ENDPOINT: !Ref TriviaBackendEndpoint
      Events:
        Canary:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: !Sub |
              {
                "sessionId": "canary-session",
                "sessionState": {
                  "sessionAttributes": {},
                  "intent": {
                    "name": "LetsPlay",
                    "slots": {},
                    "state": "InProgress"
                  }
                },
                "bot": {
                  "id": "${TriviaBot}",
                  "aliasId": "${BotAlias.BotAliasId}"
                }
              }
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref BotLatestVersionErrorMetricGreaterThanZeroAlarm
          - !Ref BotAliasErrorMetricGreaterThanZeroAlarm
        Hooks:
          PreTraffic: !Ref PreTrafficHook

  BotAliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: !Sub ${AWS::StackName}-BotAliasErrors
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${BotFunction}:live"
        - Name: FunctionName
          Value: !Ref BotFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  BotLatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: !Sub ${AWS::StackName}-BotLatestVersionErrors
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${BotFunction}:live"
        - Name: FunctionName
          Value: !Ref BotFunction
        - Name: ExecutedVersion
          Value: !GetAtt BotFunction.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  PreTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join
        - '-'
        - - 'CodeDeployHook_'
          - !Ref "AWS::StackName"
          - 'pre-traffic-hook'
      CodeUri: ./hook
      Timeout: 300
      Handler: pre-traffic-hook.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: !Sub "${BotFunction.Arn}:*"
      Runtime: nodejs20.x
      DeploymentPreference:
        Enabled: false
        Role: ""
      Environment:
        Variables:
          CurrentVersion: !Ref BotFunction.Version

  LexPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BotFunction.Alias
      Action: "lambda:invokeFunction"
      Principal: lexv2.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:lex:${AWS::Region}:${AWS::AccountId}:bot-alias/${TriviaBot}/${BotAlias.BotAliasId}'
